# Generated by Django 4.1.7 on 2023-03-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_matchaimage_shopinfo_order_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
