# Generated by Django 4.1.7 on 2023-03-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_shopinfo_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopinfo',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
