# Generated by Django 4.1.7 on 2023-03-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_shopinfo_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='shop_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='addr',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='national',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nick_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='tel',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
